### ISSUE TITLE
Window opened by it gets blocked by the browser.

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidatorappAPI#6] opened 2015-09-24 07:10 UTC
This could be an Afra only issue, or a general problem for which we might be able to implement / provide a workaround?

**Comment by yeban** [comment] 2015-09-24 07:11
This could be an Afra only issue, or a general problem for which we might be able to implement / provide a workaround?

**Comment by IsmailM** [comment] 2015-09-27 10:12
Basically, the new tab can not be opened if the action is not invoked by the user (clicking a button or something) or if it is asynchronous. This is an issue because if the GeneValidator calculation isn't async (it currently works via a promise), it blocks the browser, which is probably worse.

If you want, I don't mind having a look at your implementation in afra and see if I can come up with a work around that works?

**Comment by yeban** [comment] 2015-09-28 09:54
Here - https://github.com/wurmlab/afra/commit/7b6bdfd56287cebbde455ac765aaeee560d697bb.

In SequenceServer I avoid the popup problem due to opening results in a new page (this stuff is in master) by letting the browser handle it: `<form method=... target="_blank">`. Not sure if and how something like can be done for Afra-GV integration.

Generally, reacting to 'onclick' doesn't trigger the popup issue. I wonder if instead of GV I open the new tab myself in the click handler, will that avoid this problem.

**Comment by IsmailM** [comment] 2015-09-28 13:08
Basically the issue is that `GV.sendToGeneValidator()` is inside the `getRefSeq` function - which is asynchronous. As a result, `GV.sendToGeneValidator()` attempts to open the new tab inside a callback - which means browsers will see it as a potential pop-up. Therefore the new tab needs to be opened before the `getRefSeq` function.

Thus try the following.
1. Above the `getRefSeq` function, open the loading page and assign it to a variable. As this will be directly linked to the user click (i.e. outside the refseq function), and so will (hopefully) open instantly.
2. Next, Run the `getRefSeq` function, in which you would call the  `GV.sendToGeneValidator()` function. Change this slightly, so that you return the url of the results file.
3. Then change the url of the already open tab to the results page.

``` javascript
var loadingUrl = 'http://genevalidator.sbcs.qmul.ac.uk/GeneValidator/loading.html';
var resultsPage = window.open(loading_url, '_blank');

var finalResultsUrl = '';
this.getRefSeq(function (refSeq) {
    ...
    finalResultsUrl = GV.sendToGeneValidator('http://genevalidator.sbcs.qmul.ac.uk', fasta.join("\n"), 'SwissProt', 'all', 'results_url' );
});

resultsPage.location.href = finalResultsUrl

```

I haven’t tried this - so all I can say is that this _should_ work but let me know either way and we can go from there.

Also note, I’ve change the db name to ‘SwissProt’ since we currently don’t host ‘nr' on http://genevalidator.sbcs.qmul.ac.uk - as the BLASt is running on the nuc.

I’ll add this to the documentation when I get a chance.

**Comment by yeban** [comment] 2015-10-01 11:22
Thanks. Seems like it will work, but need the promise from gvapi to harvest the result url (#8).

If gvapi returned the promise, I could have done something like: `GV.sendToGeneValidator(...).then(function (url) { resultsPage.location.href = url; })`

**Closed as completed** 2015-10-12 08:24 UTC
